<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_view() for node entities.
 */
function ffw_database_api_node_view(
  array &$build,
  EntityInterface $node,
  EntityViewDisplayInterface $display,
  $view_mode
) {
  if (!$node->isNew() && $view_mode == 'full' && node_is_page($node) && empty($node->in_preview)) {
    $build['#attached']['library'][] = 'ffw_database_api/drupal.statistics';
    $build['#attached']['library'][] = 'ffw_database_api/load_statistics';
    $settings = [
      'data' => [
        'nid' => $node->id()
      ],
      'url' => '/ffw_statistics',
    ];
    $build['#attached']['drupalSettings']['ffwStatistics'] = $settings;
    $build['statistics'] = Drupal::service('ffw_database_api.build_statistics')->build($node->id());
    $build['statistics']['#weight'] = -10;
  }
}

/**
 * Implements hook_cron().
 */
function ffw_database_api_cron() {
  $statistics_timestamp = Drupal::state()->get('ffw_statistics.day_timestamp', 0);
  $request_time = Drupal::requestStack()->getCurrentRequest()->server->get('REQUEST_TIME');

  $is_first_hour_since_midnight = $request_time % 86400 < 3600;
  if (($request_time - $statistics_timestamp) >= 86400 && $is_first_hour_since_midnight) {
    Drupal::state()->set('ffw_statistics.day_timestamp', $request_time);
    Drupal::database()->update('ffw_entity_views_counter')
      ->fields(['todaycount' => 0])
      ->execute();
  }
}

/**
 * Implements hook_theme().
 */
function ffw_database_api_theme($existing, $type, $theme, $path): array {
  return [
    'ffw_node_view_statistics' => [
      'variables' => [
        'today' => NULL,
        'total' => NULL,
        'last_view_date' => NULL,
        'username' => NULL,
        'nid' => NULL,
        'blur' => NULL,
      ],
    ],
  ];
}
